### ISSUE TITLE
"Smash I" Regressive Cases

### ISSUE THREAD

**Issue by jnoecker** [evllabs/JGAAP#105]
Current implementation of the "Smash I" canonicizer will fail for cases where I is not strictly whitespace delineated (on either side).  Examples:

"I am here", she said.
I'm here.
It is I.

**Comment by DavidBerdik** [comment]
Nice catch. I completely forgot about contractions when writing this (obviously). Before I fix this, I want to make sure that I do not miss anything.

Contractions that have "I" that come to mind:
- I'm
- I've
- I'll
- I'd

Wikipedia also lists these two, but I have not ever seen them used and have not been able to verify their legitimacy. Perhaps someone could weigh in on this?
- I'm'a (I am about to)
- I'm'o (I am going to)

Am I missing anything? Anyone that has anything to add to this is welcome to, but I would especially like to hear @juola 's thoughts on this.

**Comment by DavidBerdik** [comment]
Fixed in 2681f55
