### ISSUE TITLE
Anti-stylometry component?

### ISSUE THREAD

**Issue by HulaHoopWhonix** [evllabs/JGAAP#107]
Hi Whonix dev here. Whonix is a Tor centric privacy distro similar to Tails but leverages VMs to provide app isolation. Our goal is to assemble a toolbox to protect activists' anonymity and we realize that masking location IP while an important step, is not enough to protect our users from advanced adversaries that use stylometry. 

We would appreciate it if you consider adding an anti-stylometry component to your suite to protect users against the techniques used to deanonymize them. Afterwards we can work with you on getting your software packaged for Debian so we can distribute it to our users.

Unfortunately the widely publicized anti-stylometry tool "Anonymouth" has many serious bugs and its repo has been dead for years. 

cc/ @adrelanos

**Comment by juola** [comment]
Hi, Whonix,

Thank you very much for your interest in the JGAAP project.   Your privacy
distro is of tremendous interest to us, and we'd love to see our software
included in the package, but there are two slight issues.

1) What you ask isn't really part of the JGAAP functionality
and
2) We don't know how to do it.

**Comment by juola** [comment]
Whonix,

I'm sorry, my computer hiccuped and sent the previous email before I was
finished with it.

To expand on my previous sardonic comments,.... automatic anonymization is
HARD.   There are so many features that have been demonstrated to be useful
for authorial analysis (about twenty years ago, a researcher named Joseph
Rudman estimated that there were more than a thousand feature SETS that had
been proposed), and most of them are sufficiently subtle that it's not easy
to analyze the effect of changing them with a computer.   For example, one
feature that has been shown to work well is the distribution of character
bigrams (two character clusters).   I, for example, might use too many
instances of "ti" and too few of "sh."   It's not clear how to adjust text
automatically to normalize these distributions without fundamentally
changing the meaning.

As it happens, this is a problem we are currently working on in
collaboration with a team at Indiana University; there are a few promising
avenues we would like to explore, and I would be delighted to discuss these
and other approaches with you.  But at the moment, this is definitely
blue-sky research and not something that we could easily put into a system
for distribution to the general public.

The other issue is that JGAAP is an analysis tool, and not a re-writing
tool.  Essentially, you can feed documents in (via a rather cumbersome
process) and it will output an attribution; we have some other software
lying around, essentially a shell script wrapped around JGAAP, that will
accept two documents and output "yes" or "no" (meaning, "yes, they're by
the same author" or "no, they're not").  But we don't really have editing
capacities, so we can't, for example, just underline all the passages that
"read like you" in blue as a Microsoft Word plugin or the equivalent.
There's a lot of UX expertise and software development that would need to
go into producing a useful anti-stylometry tool.   That's not even on the
horizon right now, although it's on the white board as an eventual
wish-list.

Again, I'd love to discuss this with you in more depth.  I agree that this
capacity is important, and I also agree that JGAAP might provide some of
the underlying technology to develop that capacity, but there's a
tremendous amount of person-months of development by skilled software
engineers between what we have now and what you want.   If you would like
to talk to me about what you want, I will listen with interest and see what
I can do, but it won't be simple and it won't be quick.

I'm available for discussion at juola@mathcs.duq.edu if you don't want to
keep using the JGAAP request channel, and I hope to hear from you soon.

Warmest regards,

(Dr) Patrick (Juola)
Director, EVL Lab
Duquesne University

**Comment by HulaHoopWhonix** [comment]
Thanks for the informative reply. I will get in touch with you via email. Feel free to close or update this ticket as the discussion develops.

**Comment by HulaHoopWhonix** [comment]
Dr. @juola I emailed you last week please check your spam folder. If you saw my message take your time.

**Comment by juola** [comment]
I saw the message but want to respond in a considered manner.  Sorry about
the apparent radio silence.
