### ISSUE TITLE
Add SVM Classification

### ISSUE THREAD

**Issue by flahi79** [evllabs/JGAAP#111]
pleas 
in version 6 has SVM Classification
If I will import to this version I find some error
can you add this classifier to this version
thank you
Ahmed Alfalahi

**Comment by DavidBerdik** [comment]
Hello @flahi79,

Linear SVM was removed from JGAAP starting with the first 7.0 Alpha build because it was replaced with WEKA SMO. Please use that instead. (changed in commit https://github.com/evllabs/JGAAP/commit/0dfa1495cbe5f2903be52b3a5e9eb9c91eabf118)

~ David Berdik
