### ISSUE TITLE
K-Nearest Neighbor Analysis Method does not provide an option to set the K parameter in the GUI.

### ISSUE THREAD

**Issue by DavidBerdik** [evllabs/JGAAP#119]
The K-Nearest Neighbor Analysis Method does not provide an option to set the K parameter in the GUI. Instead, K defaults to 5 and cannot be changed ([source](https://github.com/evllabs/JGAAP/blob/master/src/com/jgaap/classifiers/KNearestNeighborDriver.java#L50)). I do not yet know if this issue is also present when using the command line.

![image](https://user-images.githubusercontent.com/7663225/181128242-2b7242ba-51f9-42d7-8a0c-0f62ee415e92.png)

**Comment by DavidBerdik** [comment]
@Michaeljfang has opened a pull request for this: https://github.com/evllabs/JGAAP/pull/120

**Comment by DavidBerdik** [comment]
I will review soon.

**Comment by Michaeljfang** [comment]
new pull request #121

**Comment by DavidBerdik** [comment]
Thank you!
